---
addons:
  apt:
    packages:
      - aspell
      - aspell-en
      - iamerican
      - ispell
      - nodejs
      - php-cli
      - php7.0-xml
language: perl
perl:
  - blead
  - dev
  - '5.28'
  - '5.26'
  - '5.24'
  - '5.22'
  - '5.20'
  - '5.18'
  - '5.16'
  - '5.14'
  - '5.12'
  - '5.10'
cache:
  directories:
    - $HOME/perl5
    - $TRAVIS_BUILD_DIR/node_modules
    - $TRAVIS_BUILD_DIR/php5
matrix:
  allow_failures:
    - perl: blead
    - perl: dev
  fast_finish: 1
  include:
    - env: TIDYALL_TEST_DEPS=1
      perl: '5.28'
    - env: COVERAGE=1
      perl: '5.28'
    - env:
        - AUTHOR_TESTING=0
        - RELEASE_TESTING=0
      perl: '5.8'
env:
  global:
    - AUTHOR_TESTING=1
    - RELEASE_TESTING=1
before_install:
  - git config --global user.email "test@example.com"
  - git config --global user.name "Test User"
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR
install:
  - cpan-install --update-prereqs --deps
  - cpan-install --update-prereqs --coverage
  # for some reason travis-perl started dropping this with the dev & blead perl
  - cpan-install Test::Warnings
before_script:
  - coverage-setup
  - ln -s $TRAVIS_BUILD_DIR/node_modules
  - ln -s $TRAVIS_BUILD_DIR/php5
script:
  # makes node_modules/.bin symlinks
  - perl Makefile.PL
  - prove -l -j$(test-jobs) $(test-files)
after_success:
  - coverage-report
after_failure:
  - cat test-mydeps-*.log
### __app_cisetup__
# ---
# force_threaded_perls: 0
# perl_caching: 1

### __app_cisetup__
